name: Create and Release Chrome Extension

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Create .pem file
        run: echo "${{ secrets.EXTENSION_PRIVATE_KEY }}" > extension_key.pem

      - name: Create .crx file
        run: |
          mkdir -p dist
          zip -r dist/extension.zip . -x '*.git*' -x 'node_modules/*' -x 'dist/*'
          npx crx pack -o dist/extension.crx -p extension_key.pem

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload .crx file to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/extension.crx
          asset_name: extension.crx
          asset_content_type: application/octet-stream
