name: Create and Release Chrome Extension

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Create .pem file
        run: echo "${{ secrets.EXTENSION_PRIVATE_KEY }}" > extension_key.pem

      - name: Create zip file
        run: |
          mkdir -p dist
          version=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')
          zip -r "dist/sourpatch-${version}.zip" . -x '*.git*' -x 'node_modules/*' -x 'dist/*'

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload zip file to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/sourpatch-${{ github.ref }}.zip
          asset_name: sourpatch-${{ github.ref }}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
